### ISSUE TITLE
General Feedback on Codebase

### ISSUE THREAD

**Issue by shebin-tw** [sajeev-srinivasan/Bull-s-Eye#9]
Great job Sajeev. You accommodated the below suggestion which we gave on 6th Sept 2022

* Created folders & moved files accordingly
* Moved the slider image setup into separate function

**Happy to see that**
you already moved the alert code outside button action
the app is working seamlessly in iPhone 8 Plus except [one issue](https://github.com/sajeev-srinivasan/Bull-s-Eye/issues/4)
you are writing test cases
you added App Icon for iPhone & AppStore
you added meaningful bundle id
you added gitignore
folder & file structure is good

Keep up the good work Sajeev

**Comment by sajeev-srinivasan** [comment]
Thank you Shebin!
